/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author Manuel MV
 */
public class EquipoProyecto extends javax.swing.JFrame {

    /**
     * Creates new form EquipoProyecto
     * @param parent
     */
    Inicio parent;
    ReqDocCon child;
    String patron;
    
    public EquipoProyecto(Inicio parent,String patron) {
        this.parent=parent;
        this.patron=patron;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ubicacion = new javax.swing.ButtonGroup();
        composicion = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbNivel = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        rdBtnEstable = new javax.swing.JRadioButton();
        rdBtnInestable = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        cmbTamaño = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        rdBtnMisma = new javax.swing.JRadioButton();
        rdBtnDistribuidos = new javax.swing.JRadioButton();
        btnSalir = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMD");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Equipo del Proyecto", 0, 0, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Selecciones las características de su equipo de proyecto:");

        jLabel2.setText("Nivel de conocimientos:");

        cmbNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Expertos", "Calificados", "Con poca experiencia" }));

        jLabel3.setText("Composición:");

        composicion.add(rdBtnEstable);
        rdBtnEstable.setText("Estable");

        composicion.add(rdBtnInestable);
        rdBtnInestable.setText("Inestable");

        jLabel4.setText("Tamaño:");

        cmbTamaño.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pequeño (1-10)", "Mediano (10-20)", "Grande (20-más)" }));

        jLabel5.setText("Ubicación:");

        ubicacion.add(rdBtnMisma);
        rdBtnMisma.setText("En una misma locación");

        ubicacion.add(rdBtnDistribuidos);
        rdBtnDistribuidos.setText("Distribuidos geograficamente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdBtnMisma)
                                .addGap(68, 68, 68))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rdBtnEstable)
                                    .addGap(37, 37, 37)
                                    .addComponent(rdBtnInestable))
                                .addComponent(cmbTamaño, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdBtnDistribuidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbNivel, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rdBtnEstable)
                    .addComponent(rdBtnInestable))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rdBtnMisma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdBtnDistribuidos)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/siguiente.png"))); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnContinuar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnLimpiar)
                    .addComponent(btnRegresar)
                    .addComponent(btnContinuar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        if(JOptionPane.showConfirmDialog(this,"¿Está seguro que desea salir?","SMD", JOptionPane.YES_NO_CANCEL_OPTION)==0){
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        cambiarPatron();
        if(child==null){
            child =new ReqDocCon(this,this.patron);
        }
        this.setVisible(false);
        child.setVisible(true);
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.parent.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarPatron();
        this.cmbNivel.setSelectedIndex(0);
        this.composicion.clearSelection();
        this.cmbTamaño.setSelectedIndex(0);
        this.ubicacion.clearSelection();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    public void limpiarPatron(){
        cambiarCaracter(this.patron, 0,'0');
        cambiarCaracter(this.patron, 1,'0');
        cambiarCaracter(this.patron, 2,'0');
        cambiarCaracter(this.patron,3,'0');
        cambiarCaracter(this.patron,4,'0');
        cambiarCaracter(this.patron, 5,'0');
        cambiarCaracter(this.patron, 6,'0');
        cambiarCaracter(this.patron, 7,'0');
        cambiarCaracter(this.patron,8,'0');
        cambiarCaracter(this.patron,9,'0');
    }
    
    public void cambiarPatron(){
        cambiarNivel();
        cambiarComposicion();
        cambiarTamaño();
        cambiarUbicacion();
    }
    
    public void cambiarUbicacion(){
        if(this.rdBtnMisma.isSelected()){
            cambiarCaracter(this.patron,8,'1');
            cambiarCaracter(this.patron,9,'0');
        }
        else if(this.rdBtnDistribuidos.isSelected()){
            cambiarCaracter(this.patron,8,'0');
            cambiarCaracter(this.patron,9,'1');
        }
    }
    
    public void cambiarTamaño(){
        if(this.cmbTamaño.getSelectedIndex()==0){
            cambiarCaracter(this.patron, 5,'1');
            cambiarCaracter(this.patron, 6,'0');
            cambiarCaracter(this.patron, 7,'0');
        }
        else if(this.cmbTamaño.getSelectedIndex()==1){
            cambiarCaracter(this.patron, 5,'0');
            cambiarCaracter(this.patron, 6,'1');
            cambiarCaracter(this.patron, 7,'0');
        }
        else{
            cambiarCaracter(this.patron, 5,'0');
            cambiarCaracter(this.patron, 6,'0');
            cambiarCaracter(this.patron, 7,'1');
        }
    }
    
    public void cambiarComposicion(){
        if(this.rdBtnEstable.isSelected()){
            cambiarCaracter(this.patron,3,'1');
            cambiarCaracter(this.patron,4,'0');
        }
        else if(this.rdBtnInestable.isSelected()){
            cambiarCaracter(this.patron,3,'0');
            cambiarCaracter(this.patron,4,'1');
        }
    }
    
    public void cambiarNivel(){
        if(this.cmbNivel.getSelectedIndex()==0){
            cambiarCaracter(this.patron, 0,'1');
            cambiarCaracter(this.patron, 1,'0');
            cambiarCaracter(this.patron, 2,'0');
        }
        else if(this.cmbNivel.getSelectedIndex()==1){
            cambiarCaracter(this.patron, 0,'0');
            cambiarCaracter(this.patron, 1,'1');
            cambiarCaracter(this.patron, 2,'0');
        }
        else{
            cambiarCaracter(this.patron, 0,'0');
            cambiarCaracter(this.patron, 1,'0');
            cambiarCaracter(this.patron, 2,'1');
        }
    }
    
    public void cambiarCaracter(String patron,int indice, char caracter){
        String resultado="";
        for(int i=0;i<patron.length();i++){
            if(i!=indice){
                resultado=resultado+patron.charAt(i);
            }
            else{
                resultado=resultado+caracter;
            }
        }
        this.patron=resultado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbNivel;
    private javax.swing.JComboBox cmbTamaño;
    private javax.swing.ButtonGroup composicion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdBtnDistribuidos;
    private javax.swing.JRadioButton rdBtnEstable;
    private javax.swing.JRadioButton rdBtnInestable;
    private javax.swing.JRadioButton rdBtnMisma;
    private javax.swing.ButtonGroup ubicacion;
    // End of variables declaration//GEN-END:variables
}
