/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author Manuel MV
 */
public class Proyecto2 extends javax.swing.JFrame {

    /**
     * Creates new form Proyecto2
     */
    Proyecto1 parent;
    RecursosYCliente child;
    String patron;
    
    public Proyecto2(Proyecto1 parent,String patron) {
        this.parent=parent;
        this.patron=patron;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mantenimiento = new javax.swing.ButtonGroup();
        Integracion = new javax.swing.ButtonGroup();
        Pruebas = new javax.swing.ButtonGroup();
        Calidad = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdBtnSiMantenimiento = new javax.swing.JRadioButton();
        rdBtnNoMantenimiento = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rdBtnSiIntegracion = new javax.swing.JRadioButton();
        rdBtnNoIntegracion = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rdBtnPruebasConstante = new javax.swing.JRadioButton();
        rdBtnPruebasNoConstante = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rdBtnCalidadAlta = new javax.swing.JRadioButton();
        rdBtnCalidadNoAlta = new javax.swing.JRadioButton();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMD");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proyecto", 0, 0, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Selecciones las características del proyecto:");

        jLabel2.setText("¿Será necesario dar mantenimiento al software en un futuro?");

        Mantenimiento.add(rdBtnSiMantenimiento);
        rdBtnSiMantenimiento.setText("Si");

        Mantenimiento.add(rdBtnNoMantenimiento);
        rdBtnNoMantenimiento.setText("No");

        jLabel3.setText("Integración de código:");

        Integracion.add(rdBtnSiIntegracion);
        rdBtnSiIntegracion.setText("Debe ser hecha de manera eficiente");

        Integracion.add(rdBtnNoIntegracion);
        rdBtnNoIntegracion.setText("No habrá integración de código");

        jLabel4.setText("Pruebas:");

        Pruebas.add(rdBtnPruebasConstante);
        rdBtnPruebasConstante.setText("Serán de manera constante");

        Pruebas.add(rdBtnPruebasNoConstante);
        rdBtnPruebasNoConstante.setText("No serán de manera constante");

        jLabel5.setText("Calidad:");

        Calidad.add(rdBtnCalidadAlta);
        rdBtnCalidadAlta.setText("La calidad del software debe ser alta");

        Calidad.add(rdBtnCalidadNoAlta);
        rdBtnCalidadNoAlta.setText("No se requiere un software de alta calidad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdBtnNoIntegracion)
                                    .addComponent(rdBtnSiIntegracion)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rdBtnSiMantenimiento)
                                        .addGap(91, 91, 91)
                                        .addComponent(rdBtnNoMantenimiento))
                                    .addComponent(rdBtnPruebasConstante)
                                    .addComponent(rdBtnPruebasNoConstante)
                                    .addComponent(rdBtnCalidadAlta)
                                    .addComponent(rdBtnCalidadNoAlta))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdBtnSiMantenimiento)
                    .addComponent(rdBtnNoMantenimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rdBtnSiIntegracion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdBtnNoIntegracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdBtnPruebasConstante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdBtnPruebasNoConstante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rdBtnCalidadAlta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdBtnCalidadNoAlta)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/siguiente.png"))); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btnContinuar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnLimpiar)
                    .addComponent(btnRegresar)
                    .addComponent(btnContinuar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        if(JOptionPane.showConfirmDialog(this,"¿Está seguro que desea salir?","SMD", JOptionPane.YES_NO_CANCEL_OPTION)==0){
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarPatron();
        this.Mantenimiento.clearSelection();
        this.Integracion.clearSelection();
        this.Pruebas.clearSelection();
        this.Calidad.clearSelection();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.parent.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        cambiarPatron();
        if(child==null){
            child =new RecursosYCliente(this,this.patron);
        }
        this.setVisible(false);
        child.setVisible(true);
    }//GEN-LAST:event_btnContinuarActionPerformed

    public void limpiarPatron(){
        cambiarCaracter(this.patron,20,'0');
        cambiarCaracter(this.patron,21,'0');
        cambiarCaracter(this.patron,34,'0');
        cambiarCaracter(this.patron,35,'0');
        cambiarCaracter(this.patron,36,'0');
        cambiarCaracter(this.patron,37,'0');
        cambiarCaracter(this.patron,38,'0');
        cambiarCaracter(this.patron,39,'0');
    }
    
    public void cambiarPatron(){
        cambiarMantenimiento();
        cambiarIntegracion();
        cambiarPruebas();
        cambiarCalidad();
    }
    
    public void cambiarCalidad(){
        if(this.rdBtnCalidadAlta.isSelected()){
            cambiarCaracter(this.patron,38,'1');
            cambiarCaracter(this.patron,39,'0');
        }
        else if(this.rdBtnCalidadNoAlta.isSelected()){
            cambiarCaracter(this.patron,38,'0');
            cambiarCaracter(this.patron,39,'1');
        }
    }
    
    public void cambiarPruebas(){
        if(this.rdBtnPruebasConstante.isSelected()){
            cambiarCaracter(this.patron,36,'1');
            cambiarCaracter(this.patron,37,'0');
        }
        else if(this.rdBtnPruebasNoConstante.isSelected()){
            cambiarCaracter(this.patron,36,'0');
            cambiarCaracter(this.patron,37,'1');
        }
    }
    
    public void cambiarIntegracion(){
        if(this.rdBtnSiIntegracion.isSelected()){
            cambiarCaracter(this.patron,34,'1');
            cambiarCaracter(this.patron,35,'0');
        }
        else if(this.rdBtnNoIntegracion.isSelected()){
            cambiarCaracter(this.patron,34,'0');
            cambiarCaracter(this.patron,35,'1');
        }
    }
    
    public void cambiarMantenimiento(){
        if(this.rdBtnSiMantenimiento.isSelected()){
            cambiarCaracter(this.patron,20,'1');
            cambiarCaracter(this.patron,21,'0');
        }
        else if(this.rdBtnNoMantenimiento.isSelected()){
            cambiarCaracter(this.patron,20,'0');
            cambiarCaracter(this.patron,21,'1');
        }
    }

    public void cambiarCaracter(String patron,int indice, char caracter){
        String resultado="";
        for(int i=0;i<patron.length();i++){
            if(i!=indice){
                resultado=resultado+patron.charAt(i);
            }
            else{
                resultado=resultado+caracter;
            }
        }
        this.patron=resultado;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Calidad;
    private javax.swing.ButtonGroup Integracion;
    private javax.swing.ButtonGroup Mantenimiento;
    private javax.swing.ButtonGroup Pruebas;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdBtnCalidadAlta;
    private javax.swing.JRadioButton rdBtnCalidadNoAlta;
    private javax.swing.JRadioButton rdBtnNoIntegracion;
    private javax.swing.JRadioButton rdBtnNoMantenimiento;
    private javax.swing.JRadioButton rdBtnPruebasConstante;
    private javax.swing.JRadioButton rdBtnPruebasNoConstante;
    private javax.swing.JRadioButton rdBtnSiIntegracion;
    private javax.swing.JRadioButton rdBtnSiMantenimiento;
    // End of variables declaration//GEN-END:variables
}
