/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author Manuel MV
 */
public class Proyecto1 extends javax.swing.JFrame {

    /**
     * Creates new form Proyecto1
     */
    ReqDocCon parent;
    Proyecto2 child;
    String patron;
    
    public Proyecto1(ReqDocCon parent,String patron) {
        this.parent=parent;
        this.patron=patron;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Implementacion = new javax.swing.ButtonGroup();
        SolucionYObjetivos = new javax.swing.ButtonGroup();
        Riesgos = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbTamaño = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbCriticidad = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        rdBtnImplementacionRapida = new javax.swing.JRadioButton();
        rdBtnImplementacionNoRapida = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rdBtnDefinidos = new javax.swing.JRadioButton();
        rdBtnNoDefinidos = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rdBtnSiRiesgos = new javax.swing.JRadioButton();
        rdBtnNoRiesgos = new javax.swing.JRadioButton();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMD");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proyecto", 0, 0, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Selecciones las características del proyecto:");

        jLabel2.setText("Tamaño:");

        cmbTamaño.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pequeño", "Mediano", "Grande" }));

        jLabel3.setText("Criticidad:");

        cmbCriticidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Baja", "Media", "Alta", " " }));

        jLabel4.setText("Implementación:");

        Implementacion.add(rdBtnImplementacionRapida);
        rdBtnImplementacionRapida.setText("Debe ser lo más antes posible");

        Implementacion.add(rdBtnImplementacionNoRapida);
        rdBtnImplementacionNoRapida.setText("No existe presión para su rápida implementación");

        jLabel5.setText("Solucion y Objetivos:");

        SolucionYObjetivos.add(rdBtnDefinidos);
        rdBtnDefinidos.setText("Estan definidos");

        SolucionYObjetivos.add(rdBtnNoDefinidos);
        rdBtnNoDefinidos.setText("Aún no estan definidos");

        jLabel6.setText("Riesgos:");

        Riesgos.add(rdBtnSiRiesgos);
        rdBtnSiRiesgos.setText("Es necesario su análisis y manejo");

        Riesgos.add(rdBtnNoRiesgos);
        rdBtnNoRiesgos.setText("No es necesario su análisis y manejo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(11, 11, 11)
                        .addComponent(rdBtnDefinidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdBtnNoDefinidos))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdBtnNoRiesgos)
                            .addComponent(rdBtnSiRiesgos)
                            .addComponent(rdBtnImplementacionNoRapida)
                            .addComponent(rdBtnImplementacionRapida)
                            .addComponent(cmbTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCriticidad, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbCriticidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdBtnImplementacionRapida))
                .addGap(3, 3, 3)
                .addComponent(rdBtnImplementacionNoRapida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdBtnNoDefinidos)
                            .addComponent(rdBtnDefinidos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rdBtnSiRiesgos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdBtnNoRiesgos)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/siguiente.png"))); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(btnContinuar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnLimpiar)
                    .addComponent(btnRegresar)
                    .addComponent(btnContinuar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        if(JOptionPane.showConfirmDialog(this,"¿Está seguro que desea salir?","SMD", JOptionPane.YES_NO_CANCEL_OPTION)==0){
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarPatron();
        this.cmbTamaño.setSelectedIndex(0);
        this.cmbCriticidad.setSelectedIndex(0);
        this.Implementacion.clearSelection();
        this.SolucionYObjetivos.clearSelection();
        this.Riesgos.clearSelection();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.parent.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        cambiarPatron();
        if(child==null){
            child =new Proyecto2(this,this.patron);
        }
        this.setVisible(false);
        child.setVisible(true);
    }//GEN-LAST:event_btnContinuarActionPerformed

    public void limpiarPatron(){
        cambiarCaracter(this.patron, 22,'0');
        cambiarCaracter(this.patron, 23,'0');
        cambiarCaracter(this.patron, 24,'0');
        cambiarCaracter(this.patron, 25,'0');
        cambiarCaracter(this.patron, 26,'0');
        cambiarCaracter(this.patron, 27,'0');
        cambiarCaracter(this.patron, 28,'0');
        cambiarCaracter(this.patron, 29,'0');
        cambiarCaracter(this.patron, 30,'0');
        cambiarCaracter(this.patron, 31,'0');
        cambiarCaracter(this.patron, 32,'0');
        cambiarCaracter(this.patron, 33,'0');
    }
    
    public void cambiarPatron(){
        cambiarTamaño();
        cambiarCriticidad();
        cambiarImplementacion();
        cambiarSolYObj();
        cambiarRiesgos();
    }

    public void cambiarRiesgos(){
        if(this.rdBtnSiRiesgos.isSelected()){
            cambiarCaracter(this.patron,32,'1');
            cambiarCaracter(this.patron,33,'0');
        }
        else if(this.rdBtnNoRiesgos.isSelected()){
            cambiarCaracter(this.patron,32,'0');
            cambiarCaracter(this.patron,33,'1');
        }
    }
    
    public void cambiarSolYObj(){
        if(this.rdBtnDefinidos.isSelected()){
            cambiarCaracter(this.patron,30,'1');
            cambiarCaracter(this.patron,31,'0');
        }
        else if(this.rdBtnNoDefinidos.isSelected()){
            cambiarCaracter(this.patron,30,'0');
            cambiarCaracter(this.patron,31,'1');
        }
    }
    
    public void cambiarImplementacion(){
        if(this.rdBtnImplementacionRapida.isSelected()){
            cambiarCaracter(this.patron,28,'1');
            cambiarCaracter(this.patron,29,'0');
        }
        else if(this.rdBtnImplementacionNoRapida.isSelected()){
            cambiarCaracter(this.patron,28,'0');
            cambiarCaracter(this.patron,29,'1');
        }
    }
    
    public void cambiarCriticidad(){
        if(this.cmbCriticidad.getSelectedIndex()==0){
            cambiarCaracter(this.patron, 25,'1');
            cambiarCaracter(this.patron, 26,'0');
            cambiarCaracter(this.patron, 27,'0');
        }
        else if(this.cmbCriticidad.getSelectedIndex()==1){
            cambiarCaracter(this.patron, 25,'0');
            cambiarCaracter(this.patron, 26,'1');
            cambiarCaracter(this.patron, 27,'0');
        }
        else{
            cambiarCaracter(this.patron, 25,'0');
            cambiarCaracter(this.patron, 26,'0');
            cambiarCaracter(this.patron, 27,'1');
        }
    }
    
    public void cambiarTamaño(){
        if(this.cmbTamaño.getSelectedIndex()==0){
            cambiarCaracter(this.patron, 22,'1');
            cambiarCaracter(this.patron, 23,'0');
            cambiarCaracter(this.patron, 24,'0');
        }
        else if(this.cmbTamaño.getSelectedIndex()==1){
            cambiarCaracter(this.patron, 22,'0');
            cambiarCaracter(this.patron, 23,'1');
            cambiarCaracter(this.patron, 24,'0');
        }
        else{
            cambiarCaracter(this.patron, 22,'0');
            cambiarCaracter(this.patron, 23,'0');
            cambiarCaracter(this.patron, 24,'1');
        }
    }
    
    public void cambiarCaracter(String patron,int indice, char caracter){
        String resultado="";
        for(int i=0;i<patron.length();i++){
            if(i!=indice){
                resultado=resultado+patron.charAt(i);
            }
            else{
                resultado=resultado+caracter;
            }
        }
        this.patron=resultado;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Implementacion;
    private javax.swing.ButtonGroup Riesgos;
    private javax.swing.ButtonGroup SolucionYObjetivos;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbCriticidad;
    private javax.swing.JComboBox cmbTamaño;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdBtnDefinidos;
    private javax.swing.JRadioButton rdBtnImplementacionNoRapida;
    private javax.swing.JRadioButton rdBtnImplementacionRapida;
    private javax.swing.JRadioButton rdBtnNoDefinidos;
    private javax.swing.JRadioButton rdBtnNoRiesgos;
    private javax.swing.JRadioButton rdBtnSiRiesgos;
    // End of variables declaration//GEN-END:variables
}
