/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import ANNs.BPN;
import javax.swing.JOptionPane;

/**
 *
 * @author Manuel MV
 */

public class RecursosYCliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    Proyecto2 parent;
    Resultados child;
    String patron;
    
    public RecursosYCliente(Proyecto2 parent,String patron) {
        this.parent=parent;
        this.patron=patron;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Recursos = new javax.swing.ButtonGroup();
        Cliente = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rdBtnMinimizarRecursos = new javax.swing.JRadioButton();
        rdBtnSuficientesRecursos = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rdBtnSiCliente = new javax.swing.JRadioButton();
        rdBtnNoCliente = new javax.swing.JRadioButton();
        btnResultados = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMD");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recursos", 0, 0, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel1.setText("Recursos:");

        Recursos.add(rdBtnMinimizarRecursos);
        rdBtnMinimizarRecursos.setText("Es necesario minimizar el uso de recursos");

        Recursos.add(rdBtnSuficientesRecursos);
        rdBtnSuficientesRecursos.setText("Existen suficientes recursos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdBtnSuficientesRecursos)
                    .addComponent(rdBtnMinimizarRecursos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rdBtnMinimizarRecursos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdBtnSuficientesRecursos)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", 0, 0, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel2.setText("Cliente:");

        Cliente.add(rdBtnSiCliente);
        rdBtnSiCliente.setText("El cliente forma parte del equipo de trabajo");

        Cliente.add(rdBtnNoCliente);
        rdBtnNoCliente.setText("El cliente no forma parte del equipo de trabajo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdBtnNoCliente)
                    .addComponent(rdBtnSiCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rdBtnSiCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdBtnNoCliente)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        btnResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/resultados.png"))); // NOI18N
        btnResultados.setText("Resultados");
        btnResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResultados)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnLimpiar)
                    .addComponent(btnRegresar)
                    .addComponent(btnResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadosActionPerformed
        cambiarPatron();
        float[] resultados = BPN.testRNA(patron);
        if(child==null){
            child =new Resultados(this,resultados);
        }
        this.setVisible(false);
        child.setVisible(true);
    }//GEN-LAST:event_btnResultadosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        if(JOptionPane.showConfirmDialog(this,"¿Está seguro que desea salir?","SMD", JOptionPane.YES_NO_CANCEL_OPTION)==0){
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarPatron();
        this.Recursos.clearSelection();
        this.Cliente.clearSelection();
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.parent.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    public void limpiarPatron(){
        cambiarCaracter(this.patron,18,'0');
        cambiarCaracter(this.patron,19,'0');
        cambiarCaracter(this.patron,40,'0');
        cambiarCaracter(this.patron,41,'0');
    }
    
    public void cambiarPatron(){
        cambiarRecursos();
        cambiarCliente();
    }

    public void cambiarCliente(){
        if(this.rdBtnSiCliente.isSelected()){
            cambiarCaracter(this.patron,40,'1');
            cambiarCaracter(this.patron,41,'0');
        }
        else if(this.rdBtnNoCliente.isSelected()){
            cambiarCaracter(this.patron,40,'0');
            cambiarCaracter(this.patron,41,'1');
        }
    }
    
    public void cambiarRecursos(){
        if(this.rdBtnMinimizarRecursos.isSelected()){
            cambiarCaracter(this.patron,18,'1');
            cambiarCaracter(this.patron,19,'0');
        }
        else if(this.rdBtnSuficientesRecursos.isSelected()){
            cambiarCaracter(this.patron,18,'0');
            cambiarCaracter(this.patron,19,'1');
        }
    }
    
    public void cambiarCaracter(String patron,int indice, char caracter){
        String resultado="";
        for(int i=0;i<patron.length();i++){
            if(i!=indice){
                resultado=resultado+patron.charAt(i);
            }
            else{
                resultado=resultado+caracter;
            }
        }
        this.patron=resultado;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Cliente;
    private javax.swing.ButtonGroup Recursos;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnResultados;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rdBtnMinimizarRecursos;
    private javax.swing.JRadioButton rdBtnNoCliente;
    private javax.swing.JRadioButton rdBtnSiCliente;
    private javax.swing.JRadioButton rdBtnSuficientesRecursos;
    // End of variables declaration//GEN-END:variables
}
