/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author Manuel MV
 */
public class ReqDocCon extends javax.swing.JFrame {

    /**
     * Creates new form ReqDocCon
     */
    EquipoProyecto parent;
    Proyecto1 child;
    String patron;
    
    public ReqDocCon(EquipoProyecto parent,String patron) {
        this.parent=parent;
        this.patron=patron;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Estado = new javax.swing.ButtonGroup();
        Estabilidad = new javax.swing.ButtonGroup();
        Documentacion = new javax.swing.ButtonGroup();
        RevisionesYControl = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdBtnDefinidos = new javax.swing.JRadioButton();
        rdBtnNoDefinidos = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rdBtnEstables = new javax.swing.JRadioButton();
        rdBtnCambiar = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rdBtnSiDocumentacion = new javax.swing.JRadioButton();
        rdBtnNoDocumentacion = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        rdBtnSiRevCon = new javax.swing.JRadioButton();
        rdBtnNoRevCon = new javax.swing.JRadioButton();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMD");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Requerimientos", 0, 0, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Selecciones las características de los requerimientos del proyecto:");

        jLabel2.setText("Estado:");

        Estado.add(rdBtnDefinidos);
        rdBtnDefinidos.setText("Ya están definidos");

        Estado.add(rdBtnNoDefinidos);
        rdBtnNoDefinidos.setText("Aún no están definidos");

        jLabel3.setText("Estabilidad:");

        Estabilidad.add(rdBtnEstables);
        rdBtnEstables.setText("Son estables");

        Estabilidad.add(rdBtnCambiar);
        rdBtnCambiar.setText("Pueden cambiar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdBtnDefinidos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addComponent(rdBtnNoDefinidos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdBtnEstables)
                            .addComponent(rdBtnCambiar))
                        .addGap(3, 3, 3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rdBtnDefinidos)
                    .addComponent(jLabel3)
                    .addComponent(rdBtnEstables))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdBtnNoDefinidos)
                    .addComponent(rdBtnCambiar))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Documentación", 0, 0, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel4.setText("¿Es necesario llevar una correcta documentación?");

        Documentacion.add(rdBtnSiDocumentacion);
        rdBtnSiDocumentacion.setText("Si");

        Documentacion.add(rdBtnNoDocumentacion);
        rdBtnNoDocumentacion.setText("No");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(rdBtnSiDocumentacion)
                .addGap(33, 33, 33)
                .addComponent(rdBtnNoDocumentacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdBtnSiDocumentacion)
                    .addComponent(rdBtnNoDocumentacion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Revisiones y Control", 0, 0, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel5.setText("¿Las revisiones y el control serán de forma estricta?");

        RevisionesYControl.add(rdBtnSiRevCon);
        rdBtnSiRevCon.setText("Si");

        RevisionesYControl.add(rdBtnNoRevCon);
        rdBtnNoRevCon.setText("No");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdBtnSiRevCon)
                .addGap(33, 33, 33)
                .addComponent(rdBtnNoRevCon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rdBtnSiRevCon)
                    .addComponent(rdBtnNoRevCon))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/siguiente.png"))); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnContinuar)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnLimpiar)
                    .addComponent(btnRegresar)
                    .addComponent(btnContinuar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        if(JOptionPane.showConfirmDialog(this,"¿Está seguro que desea salir?","SMD", JOptionPane.YES_NO_CANCEL_OPTION)==0){
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarPatron();
        this.Estado.clearSelection();
        this.Estabilidad.clearSelection();
        this.Documentacion.clearSelection();
        this.RevisionesYControl.clearSelection();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.parent.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        cambiarPatron();
        if(child==null){
            child =new Proyecto1(this,this.patron);
        }
        this.setVisible(false);
        child.setVisible(true);
    }//GEN-LAST:event_btnContinuarActionPerformed

    public void limpiarPatron(){
        cambiarCaracter(this.patron,10,'0');
        cambiarCaracter(this.patron,11,'1');
        cambiarCaracter(this.patron,12,'1');
        cambiarCaracter(this.patron,13,'0');
        cambiarCaracter(this.patron,14,'1');
        cambiarCaracter(this.patron,15,'0');
        cambiarCaracter(this.patron,16,'0');
        cambiarCaracter(this.patron,17,'1');
    }
    
    public void cambiarPatron(){
        cambiarEstado();
        cambiarEstabilidad();
        cambiarDocumentacion();
        cambiarRevYCon();   
    }
    
    public void cambiarRevYCon(){
        if(this.rdBtnSiRevCon.isSelected()){
            cambiarCaracter(this.patron,16,'1');
            cambiarCaracter(this.patron,17,'0');
        }
        else if(this.rdBtnNoRevCon.isSelected()){
            cambiarCaracter(this.patron,16,'0');
            cambiarCaracter(this.patron,17,'1');
        }
    }
    
    public void cambiarDocumentacion(){
        if(this.rdBtnSiDocumentacion.isSelected()){
            cambiarCaracter(this.patron,14,'1');
            cambiarCaracter(this.patron,15,'0');
        }
        else if(this.rdBtnNoDocumentacion.isSelected()){
            cambiarCaracter(this.patron,14,'0');
            cambiarCaracter(this.patron,15,'1');
        }
    }
    
    public void cambiarEstabilidad(){
        if(this.rdBtnEstables.isSelected()){
            cambiarCaracter(this.patron,12,'1');
            cambiarCaracter(this.patron,13,'0');
        }
        else if(this.rdBtnCambiar.isSelected()){
            cambiarCaracter(this.patron,12,'0');
            cambiarCaracter(this.patron,13,'1');
        }
    }
    
    public void cambiarEstado(){
        if(this.rdBtnDefinidos.isSelected()){
            cambiarCaracter(this.patron,10,'1');
            cambiarCaracter(this.patron,11,'0');
        }
        else if(this.rdBtnNoDefinidos.isSelected()){
            cambiarCaracter(this.patron,10,'0');
            cambiarCaracter(this.patron,11,'1');
        }
    }
    
    public void cambiarCaracter(String patron,int indice, char caracter){
        String resultado="";
        for(int i=0;i<patron.length();i++){
            if(i!=indice){
                resultado=resultado+patron.charAt(i);
            }
            else{
                resultado=resultado+caracter;
            }
        }
        this.patron=resultado;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Documentacion;
    private javax.swing.ButtonGroup Estabilidad;
    private javax.swing.ButtonGroup Estado;
    private javax.swing.ButtonGroup RevisionesYControl;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rdBtnCambiar;
    private javax.swing.JRadioButton rdBtnDefinidos;
    private javax.swing.JRadioButton rdBtnEstables;
    private javax.swing.JRadioButton rdBtnNoDefinidos;
    private javax.swing.JRadioButton rdBtnNoDocumentacion;
    private javax.swing.JRadioButton rdBtnNoRevCon;
    private javax.swing.JRadioButton rdBtnSiDocumentacion;
    private javax.swing.JRadioButton rdBtnSiRevCon;
    // End of variables declaration//GEN-END:variables
}
